#!/usr/bin/env python3
"""Generate condition i18n inventory/review artifacts for issue #486."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable


ROOT = Path(__file__).resolve().parents[2]
MESSAGES_DIR = ROOT / "web" / "messages"
OUT_DIR = ROOT / "docs" / "works"
INVENTORY_MD = OUT_DIR / "20260224_condition_i18n_inventory.md"
GLOSSARY_MD = OUT_DIR / "20260224_condition_i18n_glossary_draft.md"


@dataclass
class CondText:
    key: str
    category: str
    group: str
    en: Dict[str, Any]
    ko: Dict[str, Any]
    zh: Dict[str, Any]


def _load_messages(lang: str) -> Dict[str, Any]:
    return json.loads((MESSAGES_DIR / f"{lang}.json").read_text())


def _flatten_params(params: Dict[str, Any]) -> list[str]:
    rows: list[str] = []
    for name, val in params.items():
        if isinstance(val, dict):
            label = val.get("label", "")
            desc = val.get("desc", "")
            rows.append(f"{name}(label={label}, desc={desc})")
        elif isinstance(val, str):
            rows.append(f"{name}({val})")
    return rows


def _to_group(key: str, category: str) -> str:
    k = key.lower()
    c = category.lower()
    if any(x in k for x in ["earnings", "post_earnings", "pre_earnings", "gap_", "opening_range", "pivot_", "seasonality", "turn_of_month"]):
        return "이벤트 (Event)"
    if any(x in k for x in ["analyst", "insider", "short_interest", "short_float", "revision", "buyback_yield", "shareholder_yield"]):
        return "센티먼트 (Sentiment)"
    if any(x in k for x in ["pe_", "pb_", "ps_", "ev_", "market", "book_to_market", "earnings_yield", "fcf_yield", "dividend_yield"]):
        return "밸류에이션 (Valuation)"
    if any(x in k for x in ["roe", "roic", "roa", "roce", "margin", "quality", "piotroski", "current_ratio", "debt_", "cashflow", "gross_profitability", "interest_coverage"]):
        return "퀄리티 (Quality)"
    if any(x in c for x in ["price", "volume", "moving", "rsi", "accumulation", "breakout", "momentum", "trend", "oscillator", "risk", "time", "statistical"]):
        return "모멘텀 (Momentum)"
    return "기타"


def _load_categories() -> Dict[str, str]:
    # Categories come from backend registry, normalized here for grouping purpose.
    try:
        from screener.conditions.registry import get_condition_metadata
        import screener.conditions  # noqa: F401

        meta = get_condition_metadata()
        return {k: str(v.get("category", "other")) for k, v in meta.items()}
    except Exception:
        return {}


def _collect() -> list[CondText]:
    en = _load_messages("en").get("conditions", {})
    ko = _load_messages("ko").get("conditions", {})
    zh = _load_messages("zh").get("conditions", {})
    categories = _load_categories()

    rows: list[CondText] = []
    for key, en_entry in en.items():
        if key in {"recommended", "categories"}:
            continue
        if not isinstance(en_entry, dict) or "label" not in en_entry:
            continue
        ko_entry = ko.get(key, {})
        zh_entry = zh.get(key, {})
        category = categories.get(key, "other")
        rows.append(
            CondText(
                key=key,
                category=category,
                group=_to_group(key, category),
                en=en_entry,
                ko=ko_entry if isinstance(ko_entry, dict) else {},
                zh=zh_entry if isinstance(zh_entry, dict) else {},
            )
        )
    rows.sort(key=lambda r: (r.group, r.key))
    return rows


def _field(entry: Dict[str, Any], name: str) -> str:
    val = entry.get(name)
    return val if isinstance(val, str) else ""


def _write_inventory(rows: Iterable[CondText]) -> None:
    grouped: Dict[str, list[CondText]] = {}
    for row in rows:
        grouped.setdefault(row.group, []).append(row)

    lines: list[str] = []
    lines.append("# Condition i18n Inventory (EN/KO/ZH)")
    lines.append("")
    lines.append("- Source: `web/messages/en.json`, `web/messages/ko.json`, `web/messages/zh.json`")
    lines.append("- Generated by: `scripts/analysis/generate_condition_i18n_review.py`")
    lines.append("")
    lines.append("## Group Summary")
    for group, items in grouped.items():
        lines.append(f"- {group}: {len(items)}")
    lines.append("")

    terminology_flags = []
    for row in rows:
        ko_blob = json.dumps(row.ko, ensure_ascii=False)
        zh_blob = json.dumps(row.zh, ensure_ascii=False)
        if re.search(r"리턴", ko_blob):
            terminology_flags.append(f"- KO `리턴` 발견: `{row.key}`")
        if re.search(r"回报率|回报", zh_blob):
            terminology_flags.append(f"- ZH `回报/回报率` 발견: `{row.key}`")

    lines.append("## Persona QA Quick Flags")
    if terminology_flags:
        lines.extend(terminology_flags)
    else:
        lines.append("- No obvious terminology flags found by heuristic scan.")
    lines.append("")

    for group, items in grouped.items():
        lines.append(f"## {group}")
        lines.append("")
        for row in items:
            lines.append(f"### [{row.category}] {row.key}")
            lines.append(f"- EN label: {_field(row.en, 'label')}")
            lines.append(f"- EN desc: {_field(row.en, 'desc')}")
            lines.append(f"- EN help: {_field(row.en, 'help')}")
            lines.append(f"- EN whenToUse: {_field(row.en, 'whenToUse')}")
            lines.append(f"- EN howToRead: {_field(row.en, 'howToRead')}")
            lines.append(f"- EN caution: {_field(row.en, 'caution')}")
            lines.append(f"- EN params: {', '.join(_flatten_params(row.en.get('params', {})))}")
            lines.append("---")
            lines.append(f"- KO label: {_field(row.ko, 'label')}")
            lines.append(f"- KO desc: {_field(row.ko, 'desc')}")
            lines.append(f"- KO help: {_field(row.ko, 'help')}")
            lines.append(f"- KO whenToUse: {_field(row.ko, 'whenToUse')}")
            lines.append(f"- KO howToRead: {_field(row.ko, 'howToRead')}")
            lines.append(f"- KO caution: {_field(row.ko, 'caution')}")
            lines.append(f"- KO params: {', '.join(_flatten_params(row.ko.get('params', {})))}")
            lines.append("---")
            lines.append(f"- ZH label: {_field(row.zh, 'label')}")
            lines.append(f"- ZH desc: {_field(row.zh, 'desc')}")
            lines.append(f"- ZH help: {_field(row.zh, 'help')}")
            lines.append(f"- ZH whenToUse: {_field(row.zh, 'whenToUse')}")
            lines.append(f"- ZH howToRead: {_field(row.zh, 'howToRead')}")
            lines.append(f"- ZH caution: {_field(row.zh, 'caution')}")
            lines.append(f"- ZH params: {', '.join(_flatten_params(row.zh.get('params', {})))}")
            lines.append("")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    INVENTORY_MD.write_text("\n".join(lines))


def _write_glossary() -> None:
    rows = [
        ("Return", "수익률", "收益率", "국내/중국 투자자 커뮤니티 통용 표현"),
        ("Market Cap", "시가총액", "总市值", "거래소/증권사 표준 용어"),
        ("Drawdown", "낙폭", "回撤", "퀀트 성과지표 문맥의 표준 표현"),
        ("Volatility", "변동성", "波动率", "리스크 지표 표준 표현"),
        ("Momentum", "모멘텀", "动量", "투자전략 분류에서 고착된 용어"),
        ("Mean Reversion", "평균 회귀", "均值回归", "전략명으로 널리 통용"),
        ("Breakout", "돌파", "突破", "기술적 분석 문맥 표준"),
        ("Oversold", "과매도", "超卖", "오실레이터 계열 지표 표준"),
        ("Overbought", "과매수", "超买", "오실레이터 계열 지표 표준"),
        ("Signal", "신호", "信号", "행동 유도 문구에서 간결성 우수"),
        ("Filter", "필터", "筛选条件", "조건 노드 문맥에서 의미 명확"),
        ("Threshold", "기준값", "阈值", "수치 경계 조건 표현 일관성"),
        ("Lookback", "조회 기간", "回看周期", "기간 기반 파라미터 의미 명확"),
        ("Risk-adjusted", "위험조정", "风险调整后", "성과지표 맥락 표준"),
        ("Portfolio Weight", "포트폴리오 비중", "组合权重", "실행/리밸런싱 문맥 호환"),
    ]

    lines = [
        "# i18n Glossary Draft (Condition Domain)",
        "",
        "- Source basis: Issue #486 persona review process",
        "- Scope: condition label/desc/help/whenToUse/howToRead/caution/params",
        "",
        "## Terms",
        "",
        "| EN 원문 | KO 채택 용어 | ZH 채택 용어 | 비고/사유 |",
        "|---------|-------------|-------------|-----------|",
    ]
    for en, ko, zh, note in rows:
        lines.append(f"| {en} | {ko} | {zh} | {note} |")

    lines.extend(
        [
            "",
            "## Usage Rules",
            "- KO: 불필요한 영문 음차(예: 리턴)는 가능하면 한국 투자자 표준 용어(수익률)로 통일.",
            "- ZH: 回报率/收益率가 혼재될 경우 기본은 收益率, 맥락상 성과 총괄은 回报可容.",
            "- 수치 방향 문구는 `높을수록/낮을수록`, `이상/이하`, `범위 내`를 명시.",
            "- whenToUse/caution은 행동 가능한 문장(언제 쓰고 무엇을 피할지)으로 작성.",
        ]
    )
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    GLOSSARY_MD.write_text("\n".join(lines))


def main() -> None:
    rows = _collect()
    _write_inventory(rows)
    _write_glossary()
    print(f"Generated: {INVENTORY_MD.relative_to(ROOT)}")
    print(f"Generated: {GLOSSARY_MD.relative_to(ROOT)}")
    print(f"Conditions processed: {len(rows)}")


if __name__ == "__main__":
    main()
